spring.datasource.url=jdbc:postgresql://localhost:5432/DATABASENAME
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=YOUR_SECRET
jwt.expiration=YOUR_EXPIRATION_TIMEgit reset

spring.jpa.hibernate.ddl-auto=update

#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=false

